---
title: "Installing LaTeX"
author: "Hugh Parsonage"
date: "2 July 2016"
output: html_document
---

Note: Installing LaTeX requires administrative privileges on your machine.

# Installation guide

1. Backup your computer.
1. Update your operating system.
1. *(Optional, Windows only)* Install [Search Everything.](https://www.voidtools.com/)
2. Restart your computer.

    ### LaTeX
    
3. In your browser (which **MUST** be Safari if you are using a Mac), google and download a *distribution* -- MikTeX (for Microsoft) or MacTeX for (iOS) or TeXLive (for Linux or Windows).
4. Close your browser and ensure no programs are running. (This isn't your standard `recommendation': if you don't close everything down, it won't work.)
5. Run the installation file.
6. Restart your computer.
7. Update your installation of LaTeX. See http://tex.stackexchange.com/questions/55437/how-do-i-update-my-tex-distribution for the most up-to-date reference for your particular distribution.
8. Open up a command prompt (Windows) or terminal (iOS / Linux) and type `tex foo\bye` then hit Enter/Return. The output should be something like

    ```
    This is TeX, Version 3.14159265 < distribution >
    < path to your install > 
    No pages of output.
    Transcript written on foo.log.
    ```
    
    If the above is not returned in the console, your installation is faulty. In particular, if you get something like `'tex' is not recognized as a command`, then TeX is not available on your system path (likely because you had other programs open during the installation phase).


    
    ### Github
    
9. Sign up for Github at https://github.com
9. Email me to be added to a repo.
9. Install Github for your operating system.

    ### pdf viewer (optional)
9. You should use a pdf viewer that can tolerate updates on-the-fly. SumatraPDF is good for Windows.

    ### Sublime
    
9. Install Sublime Text 3.
9. Install Package Control
    a. Go to https://packagecontrol.io/installation, copy the text in the SUBLIME TEXT 3 tab (which probably starts with `import `)
    b. Open Sublime Text 3
    c. Type ``Ctrl + ` ``, paste the copied script, and hit Enter.
    d. Restart Sublime Text 3
9. Install LaTeXTools
    a. Open the Command Palette: `Ctrl + Shift + P`
    b. Start typing `Install package` until `Package Control: Install Package` is selected. Hit Enter.
    c. Type `LaTeXTools`. Verify the installation is proceeding by observing the `[ ==   ]` at the bottom left of the window.
    d. Restart Sublime Text 3.
9. Restart your computer.

    ### Testing
9. Go to https://github.com/HughParsonage/grattex/
9. Clone this repo (you may be prompted to confirm your browser opening another application but it is safe to do so)
9. Once cloned, open the file \code{All_elements.tex} in Sublime Text 3. (You may need to close a tab with a LaTeXTools update/installation message.)
9. In Sublime Text 3, go to `Preferences > Package Settings > LaTeXTools > Settings -- User`.
9. Search for `"builder":` which should be `"builder": "default"`.
9. Change this line to `"builder": "script"`.
9. Scroll down to `"builder settings"`, locate your operating system and modify it like the below:

```json
"windows" : {
			"script_commands": [
				"pdflatex -draftmode",
				"biber",
				"pdflatex -draftmode",
				"pdflatex -interaction=nonstopmode"
			]
		},

```

9. Return to the `All_elements.tex` tab and hit `Ctrl + B`.
9. Your console should start building with the script commands above. You should receive no errors. Any error is a failure of installation. Come and see Hugh or Cam.
